import { ExplicitDataSource } from "@nosferatu500/react-virtual-tree";

export const demoContent: { data: ExplicitDataSource } = {
    data: {
        items: {
            root: {
                index: "root",
                data: "root",
                hasChildren: true,
                children: ["child1", "child2"],
                canMove: true,
            },
            child1: {
                index: "child1",
                data: "child1",
                hasChildren: true,
                children: ["child11"],
                canMove: false,
            },
            child2: {
                index: "child2",
                data: "child2",
                hasChildren: true,
                children: ["child21", "child22", "child23", "child24", "child25", "child26", "child27", "child28"],
                canMove: false,
            },
            child21: {
                index: "child21",
                data: "child21",
                hasChildren: false,
                children: [],
                canMove: true,
            },
            child22: {
                index: "child22",
                data: "child22",
                hasChildren: false,
                children: [],
                canMove: true,
            },
            child23: {
                index: "child23",
                data: "child23",
                hasChildren: false,
                children: [],
                canMove: true,
            },
            child24: {
                index: "child24",
                data: "child24",
                hasChildren: false,
                children: [],
                canMove: true,
            },
            child25: {
                index: "child25",
                data: "child25",
                hasChildren: false,
                children: [],
                canMove: true,
            },
            child26: {
                index: "child26",
                data: "child26",
                hasChildren: false,
                children: [],
                canMove: true,
            },
            child27: {
                index: "child27",
                data: "child27",
                hasChildren: false,
                children: [],
                canMove: true,
            },
            child28: {
                index: "child28",
                data: "child28",
                hasChildren: false,
                children: [],
                canMove: true,
            },
            child11: {
                index: "child11",
                data: "child11",
                hasChildren: true,
                children: ["child111", "child112"],
                canMove: true,
            },
            child111: {
                index: "child111",
                data: "child111",
                hasChildren: false,
                children: [],
                canMove: true,
            },
            child112: {
                index: "child112",
                data: "child112",
                hasChildren: true,
                children: ["child1121", "child1122", "child1123", "child1124", "child1125"],
                canMove: true,
            },
            child1121: {
                index: "child1121",
                data: "child1121",
                hasChildren: false,
                children: [],
                canMove: true,
            },
            child1122: {
                index: "child1122",
                data: "child1122",
                hasChildren: false,
                children: [],
                canMove: true,
            },
            child1123: {
                index: "child1123",
                data: "child1123",
                hasChildren: false,
                children: [],
                canMove: true,
            },
            child1124: {
                index: "child1124",
                data: "child1124",
                hasChildren: false,
                children: [],
                canMove: true,
            },
            child1125: {
                index: "child1125",
                data: "child1125",
                hasChildren: false,
                children: [],
                canMove: true,
            },
        },
    },
};
